# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73c3f48ff81eeccee8c99426fd0b24913ebc2d14063e64b9c76b7b0149d5f539de955064df8d54ecbcb7c537cfaa3e45bf6f5359731f0f2d633b5fe92fd602fd

test:
  secret_key_base: 495a3196019a3b69291ed0b57e4f035243261447316bd2fb3852555e1f677bb6e1453c946c065366a2262b44797ca79c813966da8edd842e33bb9ecb7a1ad803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
